use gnome instead of Debian-gdm for gdm3 user/group

diff --git a/packaging/gdm3/debian/gdm3.postrm b/packaging/gdm3/debian/gdm3.postrm
--- a/packaging/gdm3/debian/gdm3.postrm
+++ b/packaging/gdm3/debian/gdm3.postrm
@@ -16,14 +16,14 @@ if [ "$1" = "purge" ] ; then
 	rm -rf /var/log/gdm3
 	rm -rf /var/cache/gdm
 	rm -f /etc/pam.d/gdm-launch-environment
-        if getent passwd Debian-gdm >/dev/null; then
+        if getent passwd gnome >/dev/null; then
                 if [ -x /usr/sbin/deluser ]; then
-                        deluser --system Debian-gdm || echo "Could not remove Debian-gdm user."
+                        deluser --system gnome || echo "Could not remove gnome user."
                 fi
         fi
-        if getent group Debian-gdm >/dev/null; then
+        if getent group gnome >/dev/null; then
                 if [ -x /usr/sbin/delgroup ]; then
-                        delgroup --system Debian-gdm || echo "Could not remove Debian-gdm group."
+                        delgroup --system gnome || echo "Could not remove gnome group."
                 fi
         fi
 fi
