finish out build script

diff --git a/tools/build b/tools/build
--- a/tools/build
+++ b/tools/build
@@ -26,10 +26,26 @@ if ! mkdir "$1_$VERSION" ; then
 	echo -n "Attempting to create directory $1_$VERSION..."
 	mkdir "$1_$VERSION"
 fi
-cd "$1_$VERSION"
 cp -r "packaging/$1/debian" "$1_$VERSION"
 cd "$1_$VERSION"
-# FIXME exclude any included debian/
+TMP="`tempfile`"
+
+cleanup () {
+	echo -n "Cleaning... "
+	rm -fv "$TMP"
+	cd ..
+}
+
+trap cleanup EXIT
+
+uscan --force-download --dehs | tee "$TMP"
+UVERSION="`xmlstarlet sel -t -v //upstream-version $TMP`"
+VERSION="`xmlstarlet sel -t -v //debian-mangled-uversion $TMP`"
+if [ "$VERSION" != "$UVERSION" ] ; then
+	echo "$VERSION != $UVERSION, aborting!" >&2
+	exit 1
+fi
+echo "Downloaded version $VERSION"
 if [ -f "../$1_$VERSION.orig.tar.gz" ] ; then
 	tar xzvf "../$1_$VERSION.orig.tar.gz" --strip-components=1
 elif [ -f "../$1_$VERSION.orig.tar.bz2" ] ; then
@@ -37,3 +53,6 @@ elif [ -f "../$1_$VERSION.orig.tar.bz2" ] ; then
 elif [ -f "../$1_$VERSION.orig.tar.xz" ] ; then
 	tar xJvf "../$1_$VERSION.orig.tar.xz" --strip-components=1
 fi
+rm -rf debian
+cp -r "../packaging/$1/debian" .
+debuild -j8 -k$DEBKEY
